# -*- python -*-
Import("*")
localenv = env.Clone()
localenv.Append(LIBS="TIdentificatorCLAS12")
localenv.Append(LIBPATH=SHLIBDIR)
localenv.Append(CPPPATH='#include')

localenv.Program(target="get_simple_tuple",source=["get_simple_tuple.cxx",shlib])
localenv.Program(target="particle_mix",source=["particle_mix.cxx",shlib])
localenv.Program(target="get_simple_tuple_rich",source=["get_simple_tuple_rich.cxx",shlib])
localenv.Program(target="particle_mix_asym",source=["particle_mix_asym.cxx",shlib])
localenv.Program(target="particle_mix_asym_clean",source=["particle_mix_asym_clean.cxx",shlib])
